cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'neovim/neovim'
tap 'monochromegane/pt'

brew 'vifm'
brew 'git'
# brew 'w3m'
brew 'tmux'
brew 'reattach-to-user-namespace' # pbcopyに必要
brew 'nkf'
brew 'neovim'
brew 'peco'
brew 'pt'

cask 'iterm2'
cask 'sourcetree'
cask 'virtualbox'
cask 'sublime-text'

# cask 'kobito'
