brew 'tree'
brew 'vifm'
# brew 'git'
# brew 'w3m'
brew 'tmux'
# brew 'reattach-to-user-namespace' # pbcopyに必要 # 2.6から不要になったらしい
brew 'nkf'
brew 'peco'
brew 'rbenv'
brew 'ruby-build'
brew 'neovim'

brew 'pt'
tap 'monochromegane/pt'



cask_args appdir: '/Applications'
cask 'visual-studio-code'
# tap 'caskroom/cask'
# cask 'iterm2'
# cask 'sourcetree'
# cask 'virtualbox' # Failed on High Sierra
# cask 'sublime-text'
# cask 'xquartz'
# cask 'kobito'
